rc3 update
- Select the correct version for the tarball. During version discovery,
  the jq_filter function was expecting the internal flag `__version`, but
  the transition from `--version` to `__version` was not made at the
  call sites. Because of this, we were always installing the most recent
  Elixir tarball.

- Add two useful debugging commands, `kx self cd` and `kx self home`.
  Updated the `kx` wrapper functions for Bash and Fish to wrap `kx self
  cd` so that a new subshell does not need to be created.

diff --git a/kx b/kx
--- a/kx
+++ b/kx
@@ -177,7 +177,7 @@ function valid_branch() {
 function download_elixir_tarball() {
   local tarball_url
   tarball_url="$(
-    read_elixir_releases --version "${version}" | jq -r '.[0].tarball_url'
+    read_elixir_releases __version "${version}" | jq -r '.[0].tarball_url'
   )" || build_failure "Reading tarball URL for ${version}"
 
   command curl -sSL "${headers[@]}" "${tarball_url}" |
@@ -346,28 +346,38 @@ export PATH="${KX_HOME}/bin:${PATH}"
 
 function kx() {
   if (($#)); then
-    if [[ "$1" = "use" ]]; then
-      shift
+    case "$1" in
+      use)
+        shift
 
-      local source_line
-      source_line="$(USERSHELL=notcsh "${KX_HOME}"/bin/kx source "${@}")" || {
-        echo >&2 "Failed to use ${*}"
-        return 1
-      }
+        local source_line
+        source_line="$(USERSHELL=notcsh "${KX_HOME}"/bin/kx source "${@}")" || {
+          echo >&2 "Failed to use ${*}"
+          return 1
+        }
 
-      if [[ -z "${source_line}" ]]; then
-        echo >&2 "Failed to use ${*}"
-        return 1
-      fi
+        if [[ -z "${source_line}" ]]; then
+          echo >&2 "Failed to use ${*}"
+          return 1
+        fi
 
-      echo "Using ${*}"
-      source "${source_line}"
-    else
-      "${KX_HOME}/bin/kx" "$@"
-    fi
-  else
-    "${KX_HOME}/bin/kx"
+        echo "Using ${*}"
+        source "${source_line}"
+        return
+        ;;
+      self)
+        shift
+
+        if (($#)) && [[ "$2" == cd ]]; then
+          shift
+          cd "$("${KX_HOME}"/bin/kx self home "${@}")"
+          return
+        fi
+        ;;
+    esac
   fi
+
+  "${KX_HOME}/bin/kx" "$@"
 }
 EOF
 }
@@ -408,20 +418,32 @@ set -gx PATH $KX_HOME/bin $PATH
 test -f $KX_HOME/elixirs/.default.fish; and source $KX_HOME/elixirs/.default.fish
 
 function kx
-    if set -q argv[1]; and test $argv[1] = use
-        set -e argv[1]
-        set -lx USERSHELL $SHELL
+    if set -q argv[1]
+        switch $argv[1]
+            case use
+                set -e argv[1]
+                set -lx USERSHELL $SHELL
 
-        if ! set -l source_line ($KX_HOME/bin/kx source $argv); or test -z "$source_line"
-            echo "Failed to use $argv" >&2
-            return 1
-        else
-            source $source_line
-            echo "Using $argv"
+                if ! set -l source_line ($KX_HOME/bin/kx source $argv); or test -z "$source_line"
+                    echo "Failed to use $argv" >&2
+                    return 1
+                end
+
+                source $source_line
+                echo "Using $argv"
+
+                return 0
+            case self
+                set -e argv[1]
+                if set -q argv[1] && test $argv[1] == cd
+                    set -e argv[1]
+                    cd ($KX_HOME/bin/kx self home)
+                    return 0
+                end
         end
-    else
-        $KX_HOME/bin/kx $argv
     end
+
+    $KX_HOME/bin/kx $argv
 end
 EOF
 }
@@ -837,6 +859,19 @@ function do_setup() {
   fi
 }
 
+function do_self_home() {
+  if (($#)); then
+    echo "${elixirs_path}/$(find_elixir_version "${@}")" || halt $?
+  else
+    echo "${KX_HOME}"
+  fi
+}
+
+function do_self_cd() {
+  cd "$(do_self_home "${@}")" || halt $?
+  exec "${SHELL}"
+}
+
 function do_self_update() {
   cd "${bin_path}" || halt 1 "Cannot change to ${bin_path}"
 
@@ -885,6 +920,8 @@ Usage: kx self COMMAND
 Commands:
 \tupdate                    Downloads and Updates kx
 \tdestruct                  Removes kx and all installed Elixirs
+\tcd [VERSION]              Change to \$KX_HOME or the Elixir version directory
+\thome                      Print the value of \$KX_HOME.
 USAGE
 }
 
@@ -894,6 +931,14 @@ function do_self() {
     --help | -h | -\? | help) halt usage: self ;;
     update) do_self_update ;;
     destruct) do_self_destruct ;;
+    cd)
+      shift
+      do_self_cd "${@}"
+      ;;
+    home)
+      shift
+      do_self_home "${@}"
+      ;;
     esac
   else
     halt 1 usage: self
@@ -1720,7 +1765,8 @@ function main() {
   i | install) runner=do_install ;;
   reinstall) runner=do_reinstall ;;
   ls | list) runner=do_list ;;
-  setup | self) requires_setup=false ;;
+  self) requires_setup=false ;;
+  setup) requires_setup=false ;;
   sh | shell) runner=do_shell ;;
   source) runner=do_source ;;
   un | uninstall) runner=do_uninstall ;;
